x-awslogs-defaults: &awslogs-defaults
  driver: awslogs
  options:
    awslogs-region: ${AWS_REGION:-ap-southeast-2}
    awslogs-group: /football-results/ec2
    awslogs-create-group: "true"

services:
  mysql:
    ports: !override []
    logging:
      <<: *awslogs-defaults
      options:
        awslogs-region: ${AWS_REGION:-ap-southeast-2}
        awslogs-group: /football-results/ec2
        awslogs-create-group: "true"
        awslogs-stream: mysql

  backend:
    build: !reset null
    image: ${ECR_REGISTRY}/${ECR_BACKEND_REPOSITORY}:${IMAGE_TAG:-latest}
    environment:
      APP_CORS_ALLOWED_ORIGIN: http://${EC2_PUBLIC_HOST:-localhost}
    ports: !override []
    logging:
      <<: *awslogs-defaults
      options:
        awslogs-region: ${AWS_REGION:-ap-southeast-2}
        awslogs-group: /football-results/ec2
        awslogs-create-group: "true"
        awslogs-stream: backend

  frontend:
    build: !reset null
    image: ${ECR_REGISTRY}/${ECR_FRONTEND_REPOSITORY}:${IMAGE_TAG:-latest}
    ports: !override
      - "80:80"
    logging:
      <<: *awslogs-defaults
      options:
        awslogs-region: ${AWS_REGION:-ap-southeast-2}
        awslogs-group: /football-results/ec2
        awslogs-create-group: "true"
        awslogs-stream: frontend
